//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB44Entities : DbContext
    {
        public DB44Entities()
            : base("name=DB44Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CorrectAnswer> CorrectAnswers { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseInstructor> CourseInstructors { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<StudentEnrollment> StudentEnrollments { get; set; }
        public virtual DbSet<StudentFee> StudentFees { get; set; }
        public virtual DbSet<FinalResult> FinalResults { get; set; }
    
        public virtual ObjectResult<Announcement_Report_Result> Announcement_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Announcement_Report_Result>("Announcement_Report");
        }
    
        public virtual ObjectResult<Course_Instructor_Report_Result> Course_Instructor_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Course_Instructor_Report_Result>("Course_Instructor_Report");
        }
    
        public virtual ObjectResult<Course_Report_Result> Course_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Course_Report_Result>("Course_Report");
        }
    
        public virtual ObjectResult<Instructor_Report_Result> Instructor_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Instructor_Report_Result>("Instructor_Report");
        }
    
        public virtual ObjectResult<Student_Enrollment_Report_Result> Student_Enrollment_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_Enrollment_Report_Result>("Student_Enrollment_Report");
        }
    
        public virtual ObjectResult<Student_Fee_Report_Result> Student_Fee_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_Fee_Report_Result>("Student_Fee_Report");
        }
    
        public virtual ObjectResult<Student_Report_Result> Student_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_Report_Result>("Student_Report");
        }
    }
}
